[bot]
token = ""
prefix = ""

owner_ids = [
        # ids here
    ]
extensions = [
        "jishaku", "cogs.owner", "cogs.errors", "cogs.help"
    ]

[bot.intents]
members = true
presences = false

[bot.allowed_mentions]
everyone = false
users = false
roles = false
replied_user = false

[bot.config]
color = 0x2F3136
error_color = 0xe74c3c

[logging]
webhook_url = ""
format = "%(asctime)s:%(levelname)s:%(name)s: %(message)s"
level = "INFO" # INFO, DEBUG 
    